name: build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore --results-directory "TestResults-${{ env.DOTNET_VERSION }}" --artifacts-path "artifact-${{ env.DOTNET_VERSION }}"

      - name: Upload build test result
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ env.DOTNET_VERSION }}
          path: TestResults-${{ env.DOTNET_VERSION }}
          
      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-build-${{ env.DOTNET_VERSION }}
          path: artifact-${{ env.DOTNET_VERSION }}